apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flask-app-tls-hlhxz 
  namespace: default
spec:
  secretName: flask-app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mukhtasar.online
  dnsNames:
  - mukhtasar.online